module.exports = [
  '//TODO: You.',
  'You had me at "Hello World!"',
  'Oh you use IE? You must like it nice and slow.',
  "Roses are #f00, Violets are #00f, show me your bar and I'll give you my foo.",
  'Girl is that ass an exception? Cause I feel the need to handle it.',
  "Hey girl are you a motherboard? Because I'll RAM you all night.",
  'Do you live in a house with windows? Cause alt tab that ass.',
  "I'll let you throw my IOException anyday, baby.",
  'Mind if I run a sniffer to see if your ports are open?',
  'How about we do some peer-to-peer sharing? Your domain or mine?',
  "I'd like to play on your laptop.",
  'Need me to unzip your files?',
  'Can I do a penetration test on your back door?',
  'If I said you had a nice <body/> would you hold it against me?',
  'My refresh rate is phenomenal.',
  'Girl, are you a FIFO data structure implemented with generics? Because you are a Queue<T>.',
  "Hey, baby, can I get a password? 'Cause I've checked you out, and now I wanna commit.",
  "Are you Google because you got everything I'm looking for.",
  'You totally spiked my traffic.',
  'Give me a handshake so I can secure this connection?',
  'Are you a node module? because I always want to require you.',
  "Girl are you css? 'cause you got class.",
  'I got a 404 in my chest.',
  'You are like a semicolon; without you everything falls apart.',
  "Would you add your number to my phone's global scope?",
  'Ready to git commit ted?',
  'If you give me the chance, you will never have to create another branch.',
  'sudo make me a sandwich.',
  'Ready to git commit ted?',
  'STDIN?',
  'You look like one well-written subroutine. Can I call you sometime?',
  "We don't need automated UI tests. You look good enough to me.",
  'Hey girl, your DOM look good from <head> to </footer>',
  'Hey girl, you wanna check out my private functions?',
  "Damn girl, you're so stacked we have try some tail recursion.",
  "Hey girl, I sure hope you're double buffered, because I'm about to expose my bits to your register.",
  'Your baud just made me overflow. Excuse me while I reinitialize my stack.',
  "Girl your query times are too long, why don't I store some procedures in you?",
  "I'd like to flip your bits.",
  'How would you like to initialize my dangling pointer?',
  "Are you my WiFi? I think we've made a connection.",
  'You make me feel all GUI inside.',
  'Computer experts have skilled fingers.',
  'Let me stick my usb drive in your usb port.',
  'Are you a keyboard, because you are my type.',
  'If they made you in c you would be a pointer to my heart.',
  '(me != me) (me += you)',
  "Are you a CPU? You're critical to the machine that is my life.",
  "Are you a motherboard? I'd love to plug in to your socket.",
  'sudo go on a date with me.',
  "I'd learn how to exit vim for you."
]
